Pullrequest Datenschutzerklärung improvements
simlar/simlar-terms-and-conditions pull request #1
Opened 2020-03-26 00:15 UTC by BenSartor

2020-03-29 19:36 UTC, jritzerfeld requested changes

2020-03-29 19:36 UTC, jritzerfeld commented on datenschutzerklaerung.txt
> +Die Verschlüsselung erfolgt von Endgerät zu Enderät (Ende-zu-Ende). Selbst die Simlar Server haben keinen Zugriff auf Gesprächihhalte. Die Betreiber der Simlar-App haben keine Möglichkeit, die Gesprä
```suggestion
Die Verschlüsselung erfolgt von Endgerät zu Endgerät (Ende-zu-Ende). Selbst die Simlar-Server haben keinen Zugriff auf Gesprächsinhalte. Die Betreiber der Simlar-App haben keine Möglichkeit, die Gespräche der App-User zu entschlüsseln oder den Inhalt zu verfolgen. Einzig der Anrufer und der Angerufene können das Gespräch entschlüsselt tätigen.
```

2020-03-29 19:36 UTC, jritzerfeld commented on datenschutzerklaerung.txt
> +Die App übermittelt ihren Versionsnamen und die Versionsnummer an die Server, um eventuelle Probleme besser nachvollziehen zu können.
```suggestion
Die App übermittelt ihren Versionsnamen und die Versionsnummer an den Simlar-Server, um eventuelle Probleme besser nachvollziehen zu können.
```

2020-03-29 19:36 UTC, jritzerfeld commented on datenschutzerklaerung.txt
> -8. Datenschutzbeauftragter
Plötzlich kein Deutsch mehr?

2020-04-01 16:39 UTC, BenSartor commented on datenschutzerklaerung.txt
> -8. Datenschutzbeauftragter
Hi @jritzerfeld,
wie immer vielen Dank!
Habe den deutschen Text wieder eingefügt. Deine anderen Kommentare haben wir eins-zu-eins übernommen.
LG
 Ben

2020-04-13 18:00 UTC, jritzerfeld commented on datenschutzerklaerung.txt
> +Diese Datenschutzerklärung soll die wichtigsten Punkte darüber, wie wir den Datenschutz gewährleisten, erläutern. Falls Sie diesbezüglich Fragen haben, wenden Sie sich bitte an das Simlar-Team oder d
```suggestion
Diese Datenschutzerklärung erläutert die wichtigsten Punkte darüber, wie wir den Datenschutz gewährleisten. Falls Sie diesbezüglich Fragen haben, wenden Sie sich bitte an das Simlar-Team oder direkt an Ben Sartor: support@simlar.org
```

2020-04-20 18:57 UTC, DennisKlipp submitted a review, later dismissed

2020-05-08 18:32 UTC, jritzerfeld submitted a review, later dismissed
Two Thumbs Up!

2020-05-13 19:28 UTC, DennisKlipp approved these changes

2020-05-13 19:29 UTC, merged